---
- name: Add FTD CDO inventory via CLI or LTP
  hosts: all
  connection: local
  tasks:
    - name: Adding FTD to CDO and cdFMC via CLI or LTP
      when: hostvars[inventory_hostname].device_type == "ftd"
      cisco.cdo.device_inventory:
        api_key: "{{ lookup('ansible.builtin.env', 'CDO_API_KEY') }}"
        region: "{{ lookup('ansible.builtin.env', 'CDO_REGION') }}"
        add:
          ftd:
            device_name: "{{ inventory_hostname }}"
            onboard_method: "{{ hostvars[inventory_hostname].onboard_method }}"
            access_control_policy: "{{ hostvars[inventory_hostname].access_control_policy }}"
            is_virtual: "{{ hostvars[inventory_hostname].is_virtual | default(omit) }}"
            performance_tier: "{{ hostvars[inventory_hostname].performance_tier | default(omit) }}"
            license: "{{ hostvars[inventory_hostname].license }}"
            serial: "{{ hostvars[inventory_hostname].serial | default(omit) }}"
            password: "{{ hostvars[inventory_hostname].password | default(omit) }}"
      register: added_device
      failed_when: (added_device.stderr is defined) and (added_device.stderr | length > 0)

    - name: Print Add FTD results
      when: added_device['cdo'] is defined
      ansible.builtin.debug:
        msg:
          "{{ added_device.cdo | default('') }}"
