---
- name: Get device inventory details from CDO irrespective of the Ansible inventory
  hosts: localhost
  tasks:
    - name: Get the CDO inventory for this tenant
      cisco.cdo.device_inventory:
        api_key: "{{ lookup('ansible.builtin.env', 'CDO_API_KEY') }}"
        region: "{{ lookup('ansible.builtin.env', 'CDO_REGION') }}"
        gather:
          device_type: "all"
      register: inventory
      failed_when: (inventory.stderr is defined) and (inventory.stderr | length > 0)

    - name: Print inventory results
      when: inventory.cdo is defined
      ansible.builtin.debug:
        msg:
          "{{ inventory.cdo | default('') }}"
